### PR TITLE
Appveyor: Produce build artifacts.

### PR DESCRIPTION
**Pull request by crayxt**
Useful for testing.

### CODE REVIEW

**Comment by crayxt** [comment]
Failed build is not related - its just download timeout happened.
@markummitchell What do you think of this? You have ready to use package in the output.

**Comment by markummitchell** [comment]
Can I download the build artifacts? I'm still learning how this works. Also - that build timeout issue seems to have disappeared (maybe it was my bad engauge.pro which is now fixed)

**Comment by crayxt** [comment]
@markummitchell Check the artifacts tab on each build, for example https://ci.appveyor.com/project/markummitchell/engauge6/build/1.0.15/artifacts

**Comment by crayxt** [comment]
Of couse build should end successfully.

**Comment by crayxt** [comment]
@markummitchell you may want to add me as collaborator on appveyor (http://www.appveyor.com/docs/team-setup), on travis I do have permissions for this project. I may need to re-run builds sometimes.

**Comment by markummitchell** [comment]
You have an admin account now.

**Pull request merged**
